### ISSUE TITLE
Code Review Module 2 - Week 1 - Day 5 [REOPEN]

### ISSUE THREAD

**Issue by gealsanchez** [fmanimashaun/Awesome-book#2]
Great work! keep on good coding!

**Comment by amentetteh** [comment]
Goog job so far!
But :
 In your index.html, reset.css is called twice.
 You can also import reset.css from styles.css

**Comment by fmanimashaun** [comment]
> 

@amentetteh thanks for pointing this out! The issue has been addressed! Cheers
